imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: map.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%ey.secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      project: %project%
    
# BC Boostrap Configuration
bc_bootstrap:
    assets_dir:  %kernel.root_dir%/../vendor/twitter/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %ey.db.driver%
        host:     %ey.db.host%
        port:     %ey.db.port%
        dbname:   %ey.db.dbname%
        user:     %ey.db.user%
        password: %ey.db.password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FoodFlow\UserBundle\Entity\User

hwi_oauth:
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            twitter: twitter_id
            facebook: facebook_id
            foursquare: foursquare_id
    connect:
      account_connector: ff_user_provider
    resource_owners:
        twitter:
            type:                twitter
            client_id:           %oauth.twitter.client.id%
            client_secret:       %oauth.twitter.client.secret%
        facebook:
            type:                 facebook
            client_id:            %oauth.facebook.client.id%
            client_secret:        %oauth.facebook.client.secret%
            scope:                "email"
        foursquare:
            type:                 foursquare
            client_id:            %oauth.foursquare.client.id%
            client_secret:        %oauth.foursquare.client.secret%