imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     3306
        dbname:   locavores
        user:     locavores
        password: locavores
        charset:  UTF8

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

hwi_oauth:
    resource_owners:
        twitter:
            type:                twitter
            client_id:           wgFNLn1h0kBORgbmMxta8A
            client_secret:       %twitter.secret%
        facebook:
            type:                 facebook
            client_id:            442769575819427
            client_secret:        %facebook.secret%
            scope:                "email"
        foursquare:
            type:                 foursquare
            client_id:            30PIXMXXAUDENYE1THK1T21OSQ5SOTCOLXCZXYZVOM2C1PCM
            client_secret:        %foursquare.secret%