parameters:
    project:
        name: "Locavores!"
        version: 0.0.2

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
