fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

twitter_login:
    pattern: /login/with-twitter
    
facebook_login:
    pattern: /login/with-facebook
    
foursquare_login:
    pattern: /login/with-foursquare

ff_web:
    resource: "@FFWebBundle/Resources/config/routing.yml"
    prefix:   /
    
ff_maps:
    resource: "@FFMapsBundle/Resources/config/routing.yml"
    prefix:   /

ff_ingredient:
    resource: "@FFEntityBundle/Controller/IngredientController.php"
    type:     annotation
    prefix:   /ingredient